# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0003_auto_20160826_0027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set([('id', 'region', 'type', 'month', 'year')]),
        ),
    ]
